package model.stateSystem;

public enum State {

    NONE,
    IN_BATTLE,
    IN_DEFENCE,
    UNDER_CONSTRUCTION,
    MEMBER_OF_SLAVER,
    MEMBER_OF_FREEDOM,
    TRUCE,
    SABOTEUR,
    CHALLENGE_WAITING,
    GRAND_FOUNDRY_UNDER_OCCUPATION, GRAND_FOUNDRY_OCCUPIED,


}
