package model.characters;

public enum Payment {

    MAINTENANCE_EXPENSE,
    FOOD_EXPENSE,
    ARMY_EXPENSE,

    EXPECTED_SALARY_INCOME,
    MEADOW_INCOME,
    ALLOY_INCOME,
    GOLD_INCOME,
    SLAVE_INCOME,
    MYSTIC_INCOME,
    WORKER_INCOME

}
