package model.characters.ai;

public enum Aspiration {
    INCREASE_PERSONAL_OFFENCE,
    INCREASE_PERSONAL_DEFENCE,
    INCREASE_PROPERTY_DEFENCE,
    ACHIEVE_HIGHER_POSITION,
    INCREASE_FOOD_PRODUCTION,
    INCREASE_ALLOY_PRODUCTION,
    INCREASE_GOLD_PRODUCTION,
    ACHIEVE_RESOURCE_BALANCE,


}
