package model.characters.ai;

public enum Aspiration {
    INCREASE_PERSONAL_OFFENCE,
    INCREASE_PERSONAL_DEFENCE,
    INCREASE_PROPERTY_DEFENCE,
    ACHIEVE_HIGHER_POSITION,

    SAVE_RESOURCES,

    UPGRADE_PROPERTY,

    GET_GOLD_INSTANTLY,
    GET_FOOD_INSTANTLY,
    GET_ALLOYS_INSTANTLY,

    INVEST_IN_GOLD_PRODUCTION,
    INVEST_IN_ALLOY_PRODUCTION,
    INVEST_IN_FOOD_PRODUCTION,

    DEPOSIT_TO_VAULT,

    SET_EXTREME_TAXES,
    SET_LOW_TAXES,
    SET_MEDIUM_TAXES,
    SET_STANDARD_TAX, TRADE_MARKET,

}
